insert into signs (
  label,
  display_name,
  type,
  expected_hand_count,
  reference_image_url,
  short_instruction,
  common_mistakes,
  is_active
) values
  ('alphabet_A', 'A', 'alphabet', 1, '/references/alphabet-a.png', 'Form the FSL letter A and keep your hand steady inside the guide frame.', 'Keep all visible fingers clearly separated from the background.', true),
  ('alphabet_B', 'B', 'alphabet', 1, '/references/alphabet-b.png', 'Form the FSL letter B and keep your hand steady inside the guide frame.', 'Keep all visible fingers clearly separated from the background.', true),
  ('alphabet_C', 'C', 'alphabet', 1, '/references/alphabet-c.png', 'Form the FSL letter C and keep your hand steady inside the guide frame.', 'Keep all visible fingers clearly separated from the background.', true),
  ('alphabet_D', 'D', 'alphabet', 1, '/references/alphabet-d.png', 'Form the FSL letter D and keep your hand steady inside the guide frame.', 'Keep all visible fingers clearly separated from the background.', true),
  ('alphabet_E', 'E', 'alphabet', 1, '/references/alphabet-e.png', 'Form the FSL letter E and keep your hand steady inside the guide frame.', 'Keep all visible fingers clearly separated from the background.', true),
  ('alphabet_F', 'F', 'alphabet', 1, '/references/alphabet-f.png', 'Form the FSL letter F and keep your hand steady inside the guide frame.', 'Keep all visible fingers clearly separated from the background.', true),
  ('alphabet_G', 'G', 'alphabet', 1, '/references/alphabet-g.png', 'Form the FSL letter G and keep your hand steady inside the guide frame.', 'Keep all visible fingers clearly separated from the background.', true),
  ('alphabet_H', 'H', 'alphabet', 1, '/references/alphabet-h.png', 'Form the FSL letter H and keep your hand steady inside the guide frame.', 'Keep all visible fingers clearly separated from the background.', true),
  ('alphabet_I', 'I', 'alphabet', 1, '/references/alphabet-i.png', 'Form the FSL letter I and keep your hand steady inside the guide frame.', 'Keep all visible fingers clearly separated from the background.', true),
  ('alphabet_J', 'J', 'alphabet', 1, '/references/alphabet-j.png', 'Form the FSL letter J and keep your hand steady inside the guide frame.', 'Keep all visible fingers clearly separated from the background.', true),
  ('alphabet_K', 'K', 'alphabet', 1, '/references/alphabet-k.png', 'Form the FSL letter K and keep your hand steady inside the guide frame.', 'Keep all visible fingers clearly separated from the background.', true),
  ('alphabet_L', 'L', 'alphabet', 1, '/references/alphabet-l.png', 'Form the FSL letter L and keep your hand steady inside the guide frame.', 'Keep all visible fingers clearly separated from the background.', true),
  ('alphabet_M', 'M', 'alphabet', 1, '/references/alphabet-m.png', 'Form the FSL letter M and keep your hand steady inside the guide frame.', 'Keep all visible fingers clearly separated from the background.', true),
  ('alphabet_N', 'N', 'alphabet', 1, '/references/alphabet-n.png', 'Form the FSL letter N and keep your hand steady inside the guide frame.', 'Keep all visible fingers clearly separated from the background.', true),
  ('alphabet_O', 'O', 'alphabet', 1, '/references/alphabet-o.png', 'Form the FSL letter O and keep your hand steady inside the guide frame.', 'Keep all visible fingers clearly separated from the background.', true),
  ('alphabet_P', 'P', 'alphabet', 1, '/references/alphabet-p.png', 'Form the FSL letter P and keep your hand steady inside the guide frame.', 'Keep all visible fingers clearly separated from the background.', true),
  ('alphabet_Q', 'Q', 'alphabet', 1, '/references/alphabet-q.png', 'Form the FSL letter Q and keep your hand steady inside the guide frame.', 'Keep all visible fingers clearly separated from the background.', true),
  ('alphabet_R', 'R', 'alphabet', 1, '/references/alphabet-r.png', 'Form the FSL letter R and keep your hand steady inside the guide frame.', 'Keep all visible fingers clearly separated from the background.', true),
  ('alphabet_S', 'S', 'alphabet', 1, '/references/alphabet-s.png', 'Form the FSL letter S and keep your hand steady inside the guide frame.', 'Keep all visible fingers clearly separated from the background.', true),
  ('alphabet_T', 'T', 'alphabet', 1, '/references/alphabet-t.png', 'Form the FSL letter T and keep your hand steady inside the guide frame.', 'Keep all visible fingers clearly separated from the background.', true),
  ('alphabet_U', 'U', 'alphabet', 1, '/references/alphabet-u.png', 'Form the FSL letter U and keep your hand steady inside the guide frame.', 'Keep all visible fingers clearly separated from the background.', true),
  ('alphabet_V', 'V', 'alphabet', 1, '/references/alphabet-v.png', 'Form the FSL letter V and keep your hand steady inside the guide frame.', 'Keep all visible fingers clearly separated from the background.', true),
  ('alphabet_W', 'W', 'alphabet', 1, '/references/alphabet-w.png', 'Form the FSL letter W and keep your hand steady inside the guide frame.', 'Keep all visible fingers clearly separated from the background.', true),
  ('alphabet_X', 'X', 'alphabet', 1, '/references/alphabet-x.png', 'Form the FSL letter X and keep your hand steady inside the guide frame.', 'Keep all visible fingers clearly separated from the background.', true),
  ('alphabet_Y', 'Y', 'alphabet', 1, '/references/alphabet-y.png', 'Form the FSL letter Y and keep your hand steady inside the guide frame.', 'Keep all visible fingers clearly separated from the background.', true),
  ('alphabet_Z', 'Z', 'alphabet', 1, '/references/alphabet-z.png', 'Form the FSL letter Z and keep your hand steady inside the guide frame.', 'Keep all visible fingers clearly separated from the background.', true),
  ('number_0', '0', 'number', 1, '/references/number-0.png', 'Form the FSL number 0 and hold the sign still for a clear reading.', 'Keep the whole hand inside the camera guide before capturing.', true),
  ('number_1', '1', 'number', 1, '/references/number-1.png', 'Form the FSL number 1 and hold the sign still for a clear reading.', 'Keep the whole hand inside the camera guide before capturing.', true),
  ('number_2', '2', 'number', 1, '/references/number-2.png', 'Form the FSL number 2 and hold the sign still for a clear reading.', 'Keep the whole hand inside the camera guide before capturing.', true),
  ('number_3', '3', 'number', 1, '/references/number-3.png', 'Form the FSL number 3 and hold the sign still for a clear reading.', 'Keep the whole hand inside the camera guide before capturing.', true),
  ('number_4', '4', 'number', 1, '/references/number-4.png', 'Form the FSL number 4 and hold the sign still for a clear reading.', 'Keep the whole hand inside the camera guide before capturing.', true),
  ('number_5', '5', 'number', 1, '/references/number-5.png', 'Form the FSL number 5 and hold the sign still for a clear reading.', 'Keep the whole hand inside the camera guide before capturing.', true),
  ('number_6', '6', 'number', 1, '/references/number-6.png', 'Form the FSL number 6 and hold the sign still for a clear reading.', 'Keep the whole hand inside the camera guide before capturing.', true),
  ('number_7', '7', 'number', 1, '/references/number-7.png', 'Form the FSL number 7 and hold the sign still for a clear reading.', 'Keep the whole hand inside the camera guide before capturing.', true),
  ('number_8', '8', 'number', 1, '/references/number-8.png', 'Form the FSL number 8 and hold the sign still for a clear reading.', 'Keep the whole hand inside the camera guide before capturing.', true),
  ('number_9', '9', 'number', 1, '/references/number-9.png', 'Form the FSL number 9 and hold the sign still for a clear reading.', 'Keep the whole hand inside the camera guide before capturing.', true),
  ('number_10', '10', 'number', 2, '/references/number-10.png', 'Form the FSL number 10 and hold the sign still for a clear reading.', 'Keep the whole hand inside the camera guide before capturing.', true)
on conflict (label) do update set
  display_name = excluded.display_name,
  type = excluded.type,
  expected_hand_count = excluded.expected_hand_count,
  reference_image_url = excluded.reference_image_url,
  short_instruction = excluded.short_instruction,
  common_mistakes = excluded.common_mistakes,
  is_active = excluded.is_active;
